library(tidyverse)
heart <- read_csv("heart.csv", col_types = "nffnnffnfnfnff")
glimpse(heart)
summary(heart)
view(heart)
set.seed(1234)
sample_set <- sample(nrow(heart), round(nrow(heart)*.75), replace = FALSE)
heart_train <- heart[sample_set, ]
heart_test <- heart[-sample_set, ]
round(prop.table(table(select(heart, heartDisease))),2)
round(prop.table(table(select(heart_train, heartDisease))),2)
round(prop.table(table(select(heart_test, heartDisease))),2)
library(e1071)
install.packages("e1071")
library(e1071)
heart_mod <- naiveBayes(heartDisease ~ ., data = heart_train, laplace = 1)
heart_mod
View(heart_mod)
heart_pred <- predict(heart_mod, heart_test, type = "class")
heart_pred_table <- table(heart_test$heartDisease, heart_pred)
heart_pred_table
sum(diag(heart_pred_table)) / nrow(heart_test)
library(tidyverse)
heart <- read_csv("heart.csv", col_types = "nffnnffnfnfnff")
glimpse(heart)
summary(heart)
set.seed(1234)
sample_set <- sample(nrow(heart), round(nrow(heart)*.80), replace = FALSE)
heart_train <- heart[sample_set, ]
heart_test <- heart[-sample_set, ]
round(prop.table(table(select(heart, heartDisease))),2)
round(prop.table(table(select(heart_train, heartDisease))),2)
round(prop.table(table(select(heart_test, heartDisease))),2)
library(e1071)
heart_mod <- naiveBayes(heartDisease ~ ., data = heart_train, laplace = 1)
heart_mod
heart_pred <- predict(heart_mod, heart_test, type = "class")
heart_pred_table <- table(heart_test$heartDisease, heart_pred)
heart_pred_table
sum(diag(heart_pred_table)) / nrow(heart_test)
plot(X="x-asis",y="y-asis",heart_pred_table)
plot(heart_pred_table)
plot(heart_pred)
save.image("~/GABRIEL/R/PRACTICAS/heart.RData")
library(readr)
Bank<-read_csv("UniversalBank.csv")
library(caTools)
set.seed(123)
split = sample.split(Bank$Online & Bank$CreditCard & Bank$`Personal Loan`, SplitRatio = 0.6)
training_set = subset(Bank, split == TRUE)
test_set = subset(Bank, split == FALSE)
View(training_set)
View(test_set)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
newNames <- c("CreditCard", "Personal Loan" , "Online", "Freq")
colnames(dinamicTable) <-newNames
dinamicTable
View(dinamicTable)
library(e1071)
data("Bank")
Bank_df = as.data.frame(Bank)
View(Bank_df)
#
#
#
data(Bank)
dinamicTable$Freq = NULL
Model_N_B = naiveBayes('Personal Loan' ~., data = dinamicTable)
View(dinamicTable)
View(dinamicTable)
View(test_set)
View(dinamicTable)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,,1])
probabilidadPersonalLoan
dinamicTable1<-table(training_set$`Personal Loan`, training_set$Online)
dinamicTable2<-table(training_set$`Personal Loan`, training_set$CreditCard)
View(dinamicTable1)
View(dinamicTable2)
View(dinamicTable1)
View(dinamicTable2)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,1,])
probabilidadPersonalLoan
View(dinamicTable)
View(dinamicTable[1,1,1])
View(dinamicTable)
View(dinamicTable[1,1,1])
View(dinamicTable)
library(readr)
Bank<-read_csv("UniversalBank.csv")
View(Bank)
library(caTools)
set.seed(123)
split = sample.split(Bank$Online & Bank$CreditCard & Bank$`Personal Loan`, SplitRatio = 0.6)
training_set = subset(Bank, split == TRUE)
test_set = subset(Bank, split == FALSE)
View(training_set)
View(test_set)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
dinamicTable
View(dinamicTable)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,1,])
probabilidadPersonalLoan
dinamicTable1<-table(training_set$`Personal Loan`, training_set$Online)
dinamicTable2<-table(training_set$`Personal Loan`, training_set$CreditCard)
View(dinamicTable1)
View(dinamicTable2)
save.image("C:\\Users\\DELL\\Documents\\GABRIEL\\R\\TareaNaïveBayes\\Tarea1")
q()
q()
q()
misDatos<-data.frame(iris)
attach(misDatos)
library(rpart)
modelo<-rpart(Species ~ Sepal.length + Sepal.Width + Petal.Length + Petal.Width,
data = misDatos, method = "class")
modelo<-rpart(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
data = misDatos, method = "class")
plot(modelo)
text(modelo, use.n=TRUE, all=TRUE, cex=0.8)
install.packages("tree")
library(tree)
modelo1<-tree(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misdatos,
method="class", split="gini")
modelo1<-tree(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misDatos,
method="class", split="gini")
plot(modelo1)
text(modelo1, all=TRUE, cex=0.6)
install.packages("party")
library(party)
modelo2<-ctree(Species ~ Sepal.Length+Sepal.Width+Petal.Length+Petal.Width,data=misDatos)
plot(modelo2)
library(tree)
misdatos<-data.frame(iris)
modelo1<-tree(Species ~ Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misdatos,
method="class", control=tree.control(nobs=150, mincut=10))
plot(modelo1)
text(modelo1, all=TRUE, cex=0.6)
predict(modelo1, iris)
modelo2<-ctree(Species~Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
data=misdatos, controls=ctree_control(maxdepth=2))
plot(modelo2)
modelo1<-tree(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misdatos,
method="class", split="gini")
plot(modelo1)
text(modelo1, all=TRUE, cex=0.8)
modelo1<-tree(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misdatos,
method="class", split="gini")
plot(modelo1)
text(modelo1, all=TRUE, cex=0.2)
text(modelo1, all=TRUE, cex=1.5)
text(modelo1, all=TRUE, cex=.5)
text(modelo1, all=TRUE, cex=0.5)
modelo1<-tree(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data=misdatos,
method="class", split="gini")
plot(modelo1)
text(modelo1, all=TRUE, cex=0.5)
#
install.packages("TH.data")
data("bodyfat", package="TH.data")
str(bodyfat)
dim(bodyfat)
attributes(bodyfat)
bodyfat[1:5,]
# dividir en subconjuntos de entrenamiento y prueba
set.seed(1234)
ind <- sample(2, nrow(bodyfat), replace=TRUE, prob=c(0.7, 0.3))
bodyfat.train <- bodyfat[ind==1,]
bodyfat.test <- bodyfat[ind==2,]
# entrenar un árbol de decisiones
library(rpart)
myFormula <- DEXfat ~ age + waistcirc + hipcirc + elbowbreadth + kneebreadth
bodyfat_rpart <- rpart(myFormula, data = bodyfat.train,
control = rpart.control(minsplit = 10))
attributes(bodyfat_rpart)
print(bodyfat_rpart$cptable)
print(bodyfat_rpart)
plot(bodyfat_rpart)
text(bodyfat_rpart, use.n=TRUE)
plot(bodyfat_rpart)
text(bodyfat_rpart, use.n=TRUE, cex = 0.5)
plot(bodyfat_rpart)
text(bodyfat_rpart, use.n=TRUE, cex = 0.7)
opt <- which.min(bodyfat_rpart$cptable[,"xerror"])
cp <- bodyfat_rpart$cptable[opt, "CP"]
bodyfat_prune <- prune(bodyfat_rpart, cp = cp)
print(bodyfat_prune)
DEXfat_pred <- predict(bodyfat_prune, newdata = bodyfat.test)
# Los valores predichos se comparan con etiquetas reales.
xlim <- range(bodyfat$DEXfat)
plot(DEXfat_pred ~ DEXfat, data = bodyfat.test, xlab = "Observed",
ylab = "Predicted", ylim = xlim, xlim = xlim, jitter=T)
abline(a = 0, b = 1)
install.packages("rpart.plog")
install.packages("rpart.plot")
rpart.plot(bodyfat_rpart)
library(rpart.plot)
rpart.plot(bodyfat_rpart)
save.image("C:\\Users\\DELL\\Documents\\GABRIEL\\R\\ArbolesDecision")
save.image("C:\\Users\\DELL\\Documents\\GABRIEL\\R\\ArbolesDecision.R")
