library(tidyverse)
heart <- read_csv("heart.csv", col_types = "nffnnffnfnfnff")
glimpse(heart)
summary(heart)
view(heart)
set.seed(1234)
sample_set <- sample(nrow(heart), round(nrow(heart)*.75), replace = FALSE)
heart_train <- heart[sample_set, ]
heart_test <- heart[-sample_set, ]
round(prop.table(table(select(heart, heartDisease))),2)
round(prop.table(table(select(heart_train, heartDisease))),2)
round(prop.table(table(select(heart_test, heartDisease))),2)
library(e1071)
install.packages("e1071")
library(e1071)
heart_mod <- naiveBayes(heartDisease ~ ., data = heart_train, laplace = 1)
heart_mod
View(heart_mod)
heart_pred <- predict(heart_mod, heart_test, type = "class")
heart_pred_table <- table(heart_test$heartDisease, heart_pred)
heart_pred_table
sum(diag(heart_pred_table)) / nrow(heart_test)
library(tidyverse)
heart <- read_csv("heart.csv", col_types = "nffnnffnfnfnff")
glimpse(heart)
summary(heart)
set.seed(1234)
sample_set <- sample(nrow(heart), round(nrow(heart)*.80), replace = FALSE)
heart_train <- heart[sample_set, ]
heart_test <- heart[-sample_set, ]
round(prop.table(table(select(heart, heartDisease))),2)
round(prop.table(table(select(heart_train, heartDisease))),2)
round(prop.table(table(select(heart_test, heartDisease))),2)
library(e1071)
heart_mod <- naiveBayes(heartDisease ~ ., data = heart_train, laplace = 1)
heart_mod
heart_pred <- predict(heart_mod, heart_test, type = "class")
heart_pred_table <- table(heart_test$heartDisease, heart_pred)
heart_pred_table
sum(diag(heart_pred_table)) / nrow(heart_test)
plot(X="x-asis",y="y-asis",heart_pred_table)
plot(heart_pred_table)
plot(heart_pred)
save.image("~/GABRIEL/R/PRACTICAS/heart.RData")
library(readr)
Bank<-read_csv("UniversalBank.csv")
library(caTools)
set.seed(123)
split = sample.split(Bank$Online & Bank$CreditCard & Bank$`Personal Loan`, SplitRatio = 0.6)
training_set = subset(Bank, split == TRUE)
test_set = subset(Bank, split == FALSE)
View(training_set)
View(test_set)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
newNames <- c("CreditCard", "Personal Loan" , "Online", "Freq")
colnames(dinamicTable) <-newNames
dinamicTable
View(dinamicTable)
library(e1071)
data("Bank")
Bank_df = as.data.frame(Bank)
View(Bank_df)
#
#
#
data(Bank)
dinamicTable$Freq = NULL
Model_N_B = naiveBayes('Personal Loan' ~., data = dinamicTable)
View(dinamicTable)
View(dinamicTable)
View(test_set)
View(dinamicTable)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,,1])
probabilidadPersonalLoan
dinamicTable1<-table(training_set$`Personal Loan`, training_set$Online)
dinamicTable2<-table(training_set$`Personal Loan`, training_set$CreditCard)
View(dinamicTable1)
View(dinamicTable2)
View(dinamicTable1)
View(dinamicTable2)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,1,])
probabilidadPersonalLoan
View(dinamicTable)
View(dinamicTable[1,1,1])
View(dinamicTable)
View(dinamicTable[1,1,1])
View(dinamicTable)
library(readr)
Bank<-read_csv("UniversalBank.csv")
View(Bank)
library(caTools)
set.seed(123)
split = sample.split(Bank$Online & Bank$CreditCard & Bank$`Personal Loan`, SplitRatio = 0.6)
training_set = subset(Bank, split == TRUE)
test_set = subset(Bank, split == FALSE)
View(training_set)
View(test_set)
dinamicTable<-table(training_set$CreditCard, training_set$Online,training_set$`Personal Loan`)
dinamicTable
View(dinamicTable)
probabilidadPersonalLoan <- dinamicTable[1,1,1] / sum(dinamicTable[1,1,])
probabilidadPersonalLoan
dinamicTable1<-table(training_set$`Personal Loan`, training_set$Online)
dinamicTable2<-table(training_set$`Personal Loan`, training_set$CreditCard)
View(dinamicTable1)
View(dinamicTable2)
save.image("C:\\Users\\DELL\\Documents\\GABRIEL\\R\\TareaNaïveBayes\\Tarea1")
q()
q()
q()
Aptitude <- c(45, 81, 65, 87, 68, 91, 77, 61, 55, 66, 82, 93, 76, 83, 61, 74)
Performance <- c(56, 74, 56, 81, 75, 84, 68, 52, 57, 82, 73, 90, 67, 79, 70, 66)
FarMisht.frame <- data.frame(Aptitude,Performance)
FM.reg <-lm(Performance ~ Aptitude, data=FarMisht.frame)
summary(FM.reg)
coefficients(FM.reg)
y en sus intervalos de confianza:
confint(FM.reg)
predict(FM.reg,data.frame(Aptitude=c(85,62)))
library(ggplot2)
ggplot(FarMisht.frame,aes(x=Aptitude,y=Performance))
geom_point()
geom_point(method=lm)
ggplot(FarMisht.frame,aes(x=Aptitude,y=Performance)) +
geom_point()+
geom_smooth(method=lm)
ggplot(FM.reg, aes(x=fitted(FM.reg), y=residuals(FM.reg)))
geom_point()
geom_hline(yintercept = 0, linetype = "dashed" )
ggplot(FM.reg, aes(x=fitted(FM.reg), y=residuals(FM.reg)))+
geom_point() +
geom_hline(yintercept = 0, linetype = "dashed" )
Aptitude <- c(45, 81, 65, 87, 68, 91, 77, 61, 55, 66, 82, 93, 76, 83, 61, 74)
Performance <- c(56, 74, 56, 81, 75, 84, 68, 52, 57, 82, 73, 90, 67, 79, 70, 66)
Personality <- c(9, 15, 11, 15, 14, 19, 12, 10, 9, 14, 15, 14, 16, 18, 15, 12)
FarMisht.frame <- data.frame(Aptitude,Performance,Personality)
FM.multreg <- lm(Performance ~ Aptitude + Personality,
data = FarMisht.frame)
summary(FM.multreg)
predict(FM.multreg, data.frame(Aptitude = c(85,62),
Personality=c(14,17)))
utils:::menuInstallPkgs()
library(scatterplot3d)
with (FarMisht.frame,
(splot <- scatterplot3d(Performance ~ Aptitude +
Personality, type = "h", pch = 19)))
